### ISSUE TITLE
DE methods does not take Gene names in first column of read counts

### ISSUE THREAD

**Issue by pradyumnasagar** [likelet/IDEA#3]
When I change the Ensembl id to gene names in my input data the analysis stops giving following error
`Error:non-numeric argument to mathematical function
`
Is there any way to overcome this? providing facility to use gene names would be more helpful.
Thank you
Pradyumna

**Comment by likelet** [comment]
Hi Pradyumna
Thanks for your suggestion!
There must be a format issue in your data matrix. I have tested the gene before  and it works well. In IDEA, the matrix data was read using a 'read.table' function in R, and the row.names applied the first column as default. Thus the basic rules for row names in R should be followed strictly, like non-duplicated, letters-started  and no '_' allowed. 
To overcome this, you can alternatively add a header to your gene name list like gene1NADPH, gene2AMPK in excel and save the file as csv format. 

![image](https://cloud.githubusercontent.com/assets/3021506/23055154/3994ff6c-f51f-11e6-9ee0-e002d4f7ebb3.png)


Can you please pasted some of your data here  so i can help you on this more specifically.
Qi

**Comment by pradyumnasagar** [comment]
Hi,
Thanks for quick reply, I have checked the data I had repeats in the data and renamed all data and had '_' and '-' as well I removed all of them but the problem still persists.
here is the head of my data.
![image](https://cloud.githubusercontent.com/assets/10559871/23056546/f070d8a4-f511-11e6-84b3-720c73a21325.png)


design:
![image](https://cloud.githubusercontent.com/assets/10559871/23056469/9806719c-f511-11e6-91c9-35f2c617b372.png)

**Comment by likelet** [comment]
I am sorry that i did not repeat the error process with gene named data matrix. I make up some data whose genenames are similar with the matrix you posted, but the error message did not appeared. 
So i am thinking that your data matrix may have some special characters, which makes the error happened.
You may  have a try that separating the matrix into less rows  and rerun the program to see wether the problem is still exist. 
Thanks.
