### ISSUE TITLE
no progressbar

### ISSUE THREAD

**Issue by pradyumnasagar** [likelet/IDEA#4]
when i try to start IDEA it gives the following error
`ERROR: could not find function "bsProgressBar"
`
was working fine  till last week, Is there any dependency im missing? 

```
Warning: Error in tag: could not find function "bsProgressBar"
Stack trace (innermost first):
    60: tag
    59: tags$div
    58: div
    57: tag
    56: tags$div
    55: div
    54: tag
    53: tags$div
    52: div
    51: tag
    50: tags$div
    49: div
    48: tag
    47: tags$div
    46: div
    45: tagList
    44: attachDependencies
    43: bootstrapPage
    42: shinyUI
     2: shiny::runApp
     1: runIDEA
Error : could not find function "bsProgressBar"

```
Thank you

**Comment by pradyumnasagar** [comment]
didn't see the new dependencies

**Comment by likelet** [comment]
Sorry for this late reply.  According to your error message, seems to be a dependency issue. As I wrote in README file, this error mainly caused by the latest version of **ShinyBS**. It removed several fancy function s that employed in IDEA including   **bsProgressBar**. 
To fix this, you have to first remove the current **ShinyBS**  package and reinstall the 0.25.0 version or type the following command:
`devtools::install_github( "likelet/shinyBS") `
PS: This error may happen at  every time that you update your packages . plz keep the ShinyBS in a constant version at your R env

**Comment by pradyumnasagar** [comment]
Thanks, it is working after removal of shinyBS(`remove.packages("shinyBS")`) and installing recommended version(`devtools::install_github( "likelet/shinyBS")`)

**Comment by pradyumnasagar** [comment]
any suggestion what dependency is needed to download report.
`
ERROR: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
`

**Comment by likelet** [comment]
actually, two packages are required for downloading report:
`rmarkdown` and `pandoc` 
if it is still not working, try update your `knitr` packages

**Comment by likelet** [comment]
Also, i remember  that i had listed this issue in FAQ of README file as follow words. 
**3. "Error: pandoc version 1.12.3 or higher is required and was not found." while clicks the download report button:**
_Answer_: If you see this message that means you upgraded your Rstudio version, the problem is still exist. This means you need a pandoc to render Rmd file into html report. You can install it from https://github.com/jgm/pandoc/releases/tag/1.15.0.6 as YiHui suggested. Then restart your Studio.
you may try this if pandoc can not be used.

**Comment by pradyumnasagar** [comment]
hi,
thanks for suggestion.
it worked after installing this version https://github.com/jgm/pandoc/releases/tag/1.15.0.6 as you suggested.
